"""Create user_prefs table

Revision ID: 612f0efbd758
Revises: 5870ba72c5ff
Create Date: 2026-04-29 09:52:33.002197

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    StoredObject,
    PasswordHash,
    FernetBackend,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.sql import table, column

import uuid
from datetime import datetime

try:
    from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
except ImportError:
    Argon2Hasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.passlib import PasslibHasher
except ImportError:
    PasslibHasher = Any  # type: ignore
try:
    from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
except ImportError:
    PwdlibHasher = Any  # type: ignore

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = "612f0efbd758"
down_revision = "5870ba72c5ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_prefs",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False, unique=True),
        sa.Column("show_favorites_only", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_prefs_user_id_user_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_prefs")),
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_prefs")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    user_table = table("user_account", column("id"))
    prefs_table = table(
        "user_prefs",
        column("id"),
        column("user_id"),
        column("show_favorites_only"),
        column("created_at"),
        column("updated_at"),
    )

    conn = op.get_bind()
    users = conn.execute(user_table.select()).fetchall()

    if users:
        op.bulk_insert(
            prefs_table,
            [
                {
                    "id": uuid.uuid4(),
                    "user_id": row.id,
                    "show_favorites_only": False,
                    "created_at": datetime.now(),
                    "updated_at": datetime.now(),
                }
                for row in users
            ],
        )


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
